version: '3.3'
services:
  postgres:
    container_name: postgres
    image: postgres:14.0-alpine
    restart: always
    ports:
    - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data/
    env_file:
      - ./.env
  portal:
    container_name: portal
    image: dvkonstantinov/portal-staff:v1
    restart: always
    ports:
    - "8001:8001"
    - "465:465"
    volumes:
      - ./django_files/static:/app/static/
      - ./django_files/media:/app/media/
    depends_on:
      - postgres
    env_file:
      - ./.env

volumes:
  static:
  media:
  db: