# Generated by Django 4.1.1 on 2022-10-11 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalUserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='media/profile_photos/full/default.jpg', upload_to='profile_photos/full/', verbose_name='Фото')),
                ('thumbnail', models.ImageField(default='media/profile_photos/thumb/default.jpg', upload_to='profile_photos/thumb/', verbose_name='Миниатюра')),
                ('job', models.CharField(blank=True, max_length=300, null=True, verbose_name='Должность')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Обо мне')),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Личный email')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('telegram', models.CharField(blank=True, max_length=150, null=True, verbose_name='Телеграм')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доп. информация',
                'verbose_name_plural': 'Доп. информация',
                'ordering': ['id'],
            },
        ),
    ]
