# Generated by Django 4.1.1 on 2022-10-11 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_additionaluserinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
