# Generated by Django 4.1.1 on 2022-10-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ForeignKey(null=True, on_delete=models.SET(1), related_name='group', to='users.group', verbose_name='Группа'),
        ),
    ]
