# Generated by Django 4.1.1 on 2022-10-11 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_additionaluserinfo_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdditionalUserInfo',
            new_name='UserInfo',
        ),
    ]
