# Generated by Django 4.1.1 on 2022-11-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_group_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='/static/images/default-avatar.jpg', upload_to='profile_photos/full/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='thumbnail',
            field=models.ImageField(default='/static/images/default-avatar.jpg', upload_to='profile_photos/thumbs/', verbose_name='Миниатюра'),
        ),
    ]
