# Generated by Django 4.1.1 on 2022-10-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(default='profile_photos/full/default.jpg', upload_to='profile_photos/full/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='thumbnail',
            field=models.ImageField(default='profile_photos/thumb/default.jpg', upload_to='profile_photos/thumb/', verbose_name='Миниатюра'),
        ),
    ]
