# Generated by Django 4.1.1 on 2022-10-17 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userinfo_photo_alter_userinfo_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(default='/media/profile_photos/full/default.jpg', upload_to='profile_photos/full/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='thumbnail',
            field=models.ImageField(default='/media/profile_photos/thumbs/default.jpg', upload_to='profile_photos/thumb/', verbose_name='Миниатюра'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Пользователь'),
        ),
    ]
