# Generated by Django 4.1.1 on 2022-12-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_photo_alter_profile_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ManyToManyField(default=1, related_name='groups', to='users.group'),
        ),
    ]
