# Generated by Django 4.1.1 on 2022-11-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_group_title'),
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='groups',
            field=models.ManyToManyField(related_name='allowed_documents', to='users.group'),
        ),
    ]
