# Generated by Django 4.1.1 on 2022-11-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_alter_document_category_alter_document_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_for_deleting',
            field=models.BooleanField(default=False, verbose_name='Помечен на удаление'),
        ),
    ]
