# Generated by Django 4.1.1 on 2022-10-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_alter_document_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='document',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='documents', to='docs.tag'),
        ),
    ]
