# Generated by Django 4.1.1 on 2022-10-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_alter_category_options_alter_document_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='documents', to='docs.tag'),
        ),
    ]
