# Generated by Django 4.1.1 on 2023-01-26 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.postcategory', verbose_name='Рубрика'),
        ),
        migrations.AddField(
            model_name='post',
            name='groups',
            field=models.ManyToManyField(help_text='Каким группам пользователей доступен пост', related_name='allowed_posts', to='users.group', verbose_name='Группы пользователей'),
        ),
    ]
